apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: nginx-crp
spec:
  policy:
    numberOfClusters: 2
    placementType: PickN
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: region
      whenUnsatisfiable: DoNotSchedule
  resourceSelectors:
  - group: ""
    kind: Namespace
    name: nginx-deployment
    version: v1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate